# This is the .github/workflows/main.yml

name: parser    # Name of the workflow

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: push

jobs:
  # Check out the following article for more inspiration on setting up a
  # standard CI/CD pipeline for most Python projects:
  # https://jarmos.netlify.app/posts/a-standard-ci-cd-pipeline-for-python-projects/
  test:
  # Include your test suite here.
  lint:
  # Lint & format your code over here.
  deploy:
    # If the test & lint jobs don't pass,
    # the deploy job willn't even execute
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key:  "dcde7ba3-540c-4f12-9f24-c144565dd73a"
          heroku_app_name: "otc-parser"
          heroku_email: "raphaelmr95@gmail.com"
          healthcheck: "https://otc-parser.herokuapp.com/healthcheck"
          rollbackonhealthcheckfailed: true
